# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sulg',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
