# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170217_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sulg',
            new_name='slug',
        ),
    ]
